apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicio-backed
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicio-backed
  template:
    metadata:
      labels:
        app: servicio-backed
    spec:
      containers:
      - name: servicio-backed
        image: 111224433.dkr.ecr.us-east-1.amazonaws.com/servicio-backed:58
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8000
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: db-oracle-col-configmap
              key: HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-oracle-col-configmap
              key: DB_NAME
        - name: USER
          valueFrom:
            configMapKeyRef:
              name: db-oracle-col-configmap
              key: USER
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: db-oracle-col-configmap
              key: PORT
        - name: PASS
          valueFrom:
            secretKeyRef:
              name: ora-pass
              key: PASS

        - name: HOST_JP
          valueFrom:
            configMapKeyRef:
              name: db-oracle-pan-configmap
              key: HOST_JP
        - name: DB_NAME_JP
          valueFrom:
            configMapKeyRef:
              name: db-oracle-pan-configmap
              key: DB_NAME_JP
        - name: USER_JP
          valueFrom:
            configMapKeyRef:
              name: db-oracle-pan-configmap
              key: USER_JP
        - name: PORT_JP
          valueFrom:
            configMapKeyRef:
              name: db-oracle-pan-configmap
              key: PORT_JP
        - name: PASS_JP
          valueFrom:
            secretKeyRef:
              name: ora-pass-pan
              key: PASS_JP

        - name: PASS_PG
          valueFrom:
            secretKeyRef:
              name: pg-pass
              key: password
        - name: HOST_PG
          valueFrom:
            configMapKeyRef:
              name: db-pg-configmap
              key: HOST
        - name: DB_NAME_PG
          valueFrom:
            configMapKeyRef:
              name: db-pg-configmap
              key: DB_NAME
        - name: USER_PG
          valueFrom:
            configMapKeyRef:
              name: db-pg-configmap
              key: USER
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---

kind: Service
apiVersion: v1
metadata:
  name: servicio-backed-svc
  namespace: dev
spec:
  selector:
    app: servicio-backed
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  #app: frontend
  name: servicio-backed-ha
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicio-backed
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20

--- 
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dev-vs-servicio-backed
  namespace: dev
spec:
  hosts: 
  - dev.apps.com
  gateways:
  - dev/dev-gateway
  http:
  - match:
    - uri:
        prefix: /credito/orquestadorotp/
    route:
    - destination:
        host: servicio-backed-svc
        port:
          number: 80
